#!/bin/sh
# Switch the active theme by repointing themes/current, then reload apps.
# usage: theme-switch.sh [theme-name]   (no arg -> rofi picker)
#
# The special "auto" theme is generated by matugen from the current
# wallpaper (see matugen-theme.sh); it is only offered if matugen exists.

THEMES_DIR="$HOME/.config/themes"
SCRIPTS="$HOME/.config/sway/scripts"

current=$(basename "$(readlink "$THEMES_DIR/current" 2>/dev/null)")

target="$1"
if [ -z "$target" ]; then
	# -L: themes dir is a stow symlink; find won't descend without it
	target=$(find -L "$THEMES_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' |
		grep -v '^current$' | sort | while IFS= read -r t; do
			[ "$t" = auto ] && ! command -v matugen >/dev/null 2>&1 && continue
			if [ "$t" = "$current" ]; then
				printf '%s   \n' "$t" # mark the active theme
			else
				printf '%s\n' "$t"
			fi
		done | rofi -dmenu -i -p "theme" | awk '{print $1}')
fi
[ -n "$target" ] || exit 0
[ -d "$THEMES_DIR/$target" ] || { echo "no such theme: $target" >&2; exit 1; }

if [ "$target" = "auto" ]; then
	# Generate the palette from the current wallpaper first, so the
	# symlink never points at a half-built theme.
	wall=$(cat "$HOME/.cache/current-wallpaper" 2>/dev/null)
	[ -f "$wall" ] || { notify-send "Theme" "auto needs a current wallpaper"; exit 1; }
	sh "$SCRIPTS/matugen-theme.sh" "$wall" || { notify-send "Theme" "matugen failed"; exit 1; }
fi

# Repoint the single source of truth. -n: replace the link itself instead
# of creating a link *inside* the directory it points to.
ln -sfn "$target" "$THEMES_DIR/current"

# GTK / icons / cursor for this theme.
[ -f "$THEMES_DIR/current/gtk.sh" ] && sh "$THEMES_DIR/current/gtk.sh"

# Wallpaper: first one in the new theme. The auto theme keeps the current
# wallpaper (its palette was just generated from it).
if [ "$target" != "auto" ]; then
	first=$(find -L "$THEMES_DIR/current/wallpapers" -type f \
		\( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) \
		2>/dev/null | sort | head -n1)
	[ -n "$first" ] && sh "$SCRIPTS/set-wallpaper.sh" "$first" --no-reload
fi

sh "$SCRIPTS/theme-reload.sh"

notify-send -a theme "Theme switched" "Now using: $target"
exit 0
