[Appearance]
style=kvantum-dark
icon_theme=Papirus-Dark
standard_dialogs=default
custom_palette=false

[Interface]
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
underline_shortcut=2
wheel_scroll_lines=3
